#
# Build profiles: `default`, `via-ir`
# Test profiles: `default`, `intense`
#
# ==================
# Profile: `default`
# ==================
[profile.default]
solc = "0.8.19"
optimizer = true
optimizer_runs = 10_000
auto_detect_solc = false
libs = ["node_modules", "lib"]

[profile.default.fuzz]
runs = 1_000

# ==================
# Profile: `intense`
# ==================
[profile.intense.fuzz]
runs = 10_000

# =================
# Profile: `via-ir`
# =================
[profile.via-ir]
via_ir = true

[profile.via-ir.fuzz]
runs = 1_000
